Import libraries** <a class="anchor" id="7"></a>

[Table of Contents](#0.1)

In [44]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # data visualization
import seaborn as sns # statistical data visualization
%matplotlib inline

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/normalized-asl-coordinates/normalize_coordinates.csv
/kaggle/input/asl-alphabet-joint-angles/joint_angle_dataset_cleaned.csv
/kaggle/input/asl-random-forrest/joint_angle_dataset_cleaned3.csv

In [45]:
import warnings

warnings.filterwarnings('ignore')

# **1. Import dataset** <a class="anchor" id="8"></a>

[Table of Contents](#0.1)

In [46]:
data = '/kaggle/input/asl-random-forrest/joint_angle_dataset_cleaned3.csv'

df = pd.read_csv(data, header=None)

# **2. Look at the Data** <a class="anchor" id="9"></a>

[Table of Contents](#0.1)

### View top 5 rows of dataset

In [48]:
# preview the dataset

df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,154.749423,150.130817,160.469365,128.149768,77.114423,148.771402,114.727540,87.970102,119.901317,101.196548,97.426783,132.230920,112.532907,107.121365,120.095491,69.174474,16.126082,28.852631,46.660766,A
1,155.882795,152.660454,159.841122,150.939983,7.660659,172.037868,154.058543,40.865287,139.810710,151.164188,43.856657,145.053570,140.065912,58.769755,131.509083,65.856174,14.401352,28.148323,44.301770,A
2,158.472180,153.135786,156.250734,145.471190,29.255226,165.427230,147.324318,53.613713,135.406461,142.757988,63.524956,138.562641,141.369751,73.528906,124.402803,62.869074,13.603507,25.565243,41.548707,A
3,157.950032,154.693798,156.333608,134.732742,62.351337,155.485062,118.801702,82.205687,127.839314,105.957712,89.228373,140.782290,114.897191,98.518286,120.875182,68.687430,15.692418,29.361264,46.937544,A
4,153.273327,155.669938,160.042219,133.969487,70.010760,152.998750,117.719919,85.101885,123.688709,104.897770,93.573398,138.363548,115.478883,103.622415,117.732633,68.519478,15.743850,29.313947,46.644718,A

### Rename column names

Give the collumns proper names.

In [49]:
col_names = ['0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18',"class"]


df.columns = col_names

col_names

['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 'class']

In [50]:
# take anothe look at the data set

df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,class
0,154.749423,150.130817,160.469365,128.149768,77.114423,148.771402,114.727540,87.970102,119.901317,101.196548,97.426783,132.230920,112.532907,107.121365,120.095491,69.174474,16.126082,28.852631,46.660766,A
1,155.882795,152.660454,159.841122,150.939983,7.660659,172.037868,154.058543,40.865287,139.810710,151.164188,43.856657,145.053570,140.065912,58.769755,131.509083,65.856174,14.401352,28.148323,44.301770,A
2,158.472180,153.135786,156.250734,145.471190,29.255226,165.427230,147.324318,53.613713,135.406461,142.757988,63.524956,138.562641,141.369751,73.528906,124.402803,62.869074,13.603507,25.565243,41.548707,A
3,157.950032,154.693798,156.333608,134.732742,62.351337,155.485062,118.801702,82.205687,127.839314,105.957712,89.228373,140.782290,114.897191,98.518286,120.875182,68.687430,15.692418,29.361264,46.937544,A
4,153.273327,155.669938,160.042219,133.969487,70.010760,152.998750,117.719919,85.101885,123.688709,104.897770,93.573398,138.363548,115.478883,103.622415,117.732633,68.519478,15.743850,29.313947,46.644718,A

We can see that the column names are renamed. Now, the columns have meaningful names.

### View summary of dataset

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55495 entries, 0 to 55494
Data columns (total 20 columns):
0        55495 non-null float64
1        55495 non-null float64
2        55495 non-null float64
3        55495 non-null float64
4        55495 non-null float64
5        55495 non-null float64
6        55495 non-null float64
7        55495 non-null float64
8        55495 non-null float64
9        55495 non-null float64
10       55495 non-null float64
11       55495 non-null float64
12       55495 non-null float64
13       55495 non-null float64
14       55495 non-null float64
15       55495 non-null float64
16       55495 non-null float64
17       55495 non-null float64
18       55495 non-null float64
class    55495 non-null object
dtypes: float64(19), object(1)
memory usage: 8.5+ MB

### Frequency distribution of values in variables

Now, I will check the frequency counts of categorical variables.

In [55]:
col_names = ['0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18']


for col in col_names:
    
    print(df[col].value_counts())

164.546574    2
164.363663    1
147.458542    1
149.844407    1
151.232204    1
             ..
165.941180    1
162.431137    1
166.905939    1
151.855226    1
163.640732    1
Name: 0, Length: 55494, dtype: int64
174.169239    2
150.294894    1
127.192524    1
159.115028    1
141.332357    1
             ..
171.200577    1
161.716230    1
162.799426    1
134.249987    1
132.753766    1
Name: 1, Length: 55494, dtype: int64
170.617260    2
143.369981    1
155.360647    1
145.554626    1
158.761419    1
             ..
147.918159    1
112.453631    1
152.010541    1
143.094473    1
153.893300    1
Name: 2, Length: 55494, dtype: int64
154.158900    2
142.995946    1
103.914723    1
154.453096    1
156.766951    1
             ..
151.902339    1
169.752105    1
115.478244    1
149.876682    1
145.805774    1
Name: 3, Length: 55494, dtype: int64
163.465759    2
177.410541    1
124.771935    1
164.549431    1
85.600514     1
             ..
171.528343    1
157.218023    1
100.753945    1
168.250720    1
160.466010    1
Name: 4, Length: 55494, dtype: int64
149.813572    2
90.085737     1
137.794197    1
139.867446    1
146.363565    1
             ..
144.050154    1
139.173834    1
146.790894    1
146.816561    1
135.387724    1
Name: 5, Length: 55494, dtype: int64
149.436225    2
125.413601    1
132.820093    1
149.798181    1
166.469637    1
             ..
164.309378    1
143.360434    1
123.665369    1
125.835698    1
143.773493    1
Name: 6, Length: 55494, dtype: int64
163.168492    2
139.386471    1
90.827370     1
167.757577    1
66.874548     1
             ..
162.727975    1
128.790138    1
174.529900    1
162.198650    1
88.646527     1
Name: 7, Length: 55494, dtype: int64
161.464803    2
128.118064    1
164.341103    1
129.374356    1
108.168271    1
             ..
176.319425    1
162.987751    1
154.193554    1
163.390888    1
102.600749    1
Name: 8, Length: 55494, dtype: int64
155.217306    2
161.452520    1
102.218226    1
132.096029    1
143.011448    1
             ..
133.702073    1
154.173000    1
140.931739    1
172.206784    1
154.880541    1
Name: 9, Length: 55494, dtype: int64
158.832826    2
92.937375     1
79.533776     1
77.881391     1
62.062456     1
             ..
89.846153     1
88.218338     1
67.305375     1
86.100965     1
154.446129    1
Name: 10, Length: 55494, dtype: int64
160.259350    2
134.879909    1
162.013724    1
144.802843    1
129.276132    1
             ..
172.650158    1
129.630381    1
128.483440    1
149.798440    1
153.421802    1
Name: 11, Length: 55494, dtype: int64
160.030335    2
127.400293    1
171.469021    1
151.415065    1
112.994242    1
             ..
148.461722    1
128.101141    1
152.375653    1
155.647066    1
114.596705    1
Name: 12, Length: 55494, dtype: int64
169.714450    2
142.488154    1
88.256461     1
94.067256     1
98.124998     1
             ..
110.640863    1
134.540863    1
146.044379    1
164.020546    1
96.429593     1
Name: 13, Length: 55494, dtype: int64
150.903745    2
125.508303    1
126.565280    1
177.000253    1
145.841028    1
             ..
145.558859    1
115.790493    1
135.181393    1
101.755259    1
126.595330    1
Name: 14, Length: 55494, dtype: int64
71.650954    2
79.870891    1
74.603075    1
77.493977    1
75.172265    1
            ..
80.697883    1
72.700144    1
75.175122    1
81.577686    1
70.887313    1
Name: 15, Length: 55494, dtype: int64
13.622664    2
8.492776     1
14.225673    1
12.240090    1
14.305228    1
            ..
13.026826    1
11.057039    1
11.985329    1
12.634355    1
16.139090    1
Name: 16, Length: 55494, dtype: int64
28.009373    2
24.441738    1
25.788353    1
19.204206    1
32.854375    1
            ..
25.803936    1
25.400014    1
36.016443    1
25.377265    1
29.725216    1
Name: 17, Length: 55494, dtype: int64
41.385557    2
34.689490    1
36.478537    1
45.663893    1
36.995453    1
            ..
40.775805    1
35.475553    1
40.907931    1
43.482649    1
39.521361    1
Name: 18, Length: 55494, dtype: int64

We can see that the `doors` and `persons` are categorical in nature. So, I will treat them as categorical variables.

### Explore `class` variable

In [56]:
df['class'].value_counts()

F    2872
K    2699
Y    2580
S    2557
V    2550
R    2549
L    2526
U    2516
D    2461
W    2455
G    2426
I    2383
H    2372
T    2358
E    2311
O    2269
B    2202
A    2193
X    2165
Q    2122
P    2047
C    1958
M    1631
N    1293
Name: class, dtype: int64

The `class` target variable is ordinal in nature.

### Missing values in variables

In [57]:
# check missing values in variables

df.isnull().sum()

0        0
1        0
2        0
3        0
4        0
5        0
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
class    0
dtype: int64

We can see that there are no missing values in the dataset. I have checked the frequency distribution of values previously. It also confirms that there are no missing values in the dataset.

# **3. Declare feature vector and target variable** <a class="anchor" id="10"></a>

[Table of Contents](#0.1)

In [59]:
X = df.drop(['class'], axis=1)

y = df['class']

# **4. Split data into separate training and test set** <a class="anchor" id="11"></a>

[Table of Contents](#0.1)

In [60]:
# split data into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [61]:
# check the shape of X_train and X_test

X_train.shape, X_test.shape

((37181, 19), (18314, 19))

# **5. Feature Engineering** <a class="anchor" id="12"></a>

[Table of Contents](#0.1)


**Feature Engineering** is the process of transforming raw data into useful features that help us to understand our model better and increase its predictive power. I will carry out feature engineering on different types of variables.


First, I will check the data types of variables again.

In [62]:
# check data types in X_train

X_train.dtypes

0     float64
1     float64
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
9     float64
10    float64
11    float64
12    float64
13    float64
14    float64
15    float64
16    float64
17    float64
18    float64
dtype: object

### Encode categorical variables


Now, I will encode the categorical variables.

In [63]:
X_train.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
52389,156.010168,135.193091,127.654188,167.605999,167.779855,140.547076,137.611867,88.404029,105.668923,118.934894,86.783842,121.218768,138.082409,101.883689,106.150760,73.904589,15.059199,27.146711,43.164794
31394,168.652469,155.973898,170.705095,117.874903,146.699255,120.388217,104.256618,136.610808,156.946768,114.556163,133.138141,160.223160,139.279606,147.068660,145.603811,69.259938,13.398526,25.727280,38.737302
8626,145.463054,158.127090,126.250436,163.181722,159.850098,154.915528,146.200033,122.636837,146.515446,146.767463,139.495319,170.617917,172.095265,145.387446,105.673108,61.719801,12.089323,24.588492,31.683527
45318,153.182543,134.751129,128.066660,171.197861,171.214088,140.947246,159.418120,171.336508,168.666516,126.583010,86.603363,144.075277,122.028813,103.059018,128.820194,70.181725,12.892734,25.025723,42.661468
49222,129.554583,152.069726,139.920190,176.216415,165.134823,152.455204,176.774797,159.075632,160.580122,172.251860,156.539290,176.401116,104.246252,125.695230,166.127454,74.985223,12.890936,21.703347,37.791730

---

In [64]:
# import category encoders

import category_encoders as ce

In [65]:
your_array = [col_names]

class_values = {}
classes = []

for i, item in enumerate(your_array):
    class_values[str(i)] = item
    classes.append(i)

encoded_classes = to_categorical(classes)

NameError: name 'to_categorical' is not defined

In [67]:
# encode categorical variables with ordinal encoding

encoder = ce.OneHotEncoder(cols=['0','1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18'])


X_train = encoder.fit_transform(X_train)

X_test = encoder.transform(X_test)

KeyboardInterrupt:

In [68]:
X_train.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
52389,156.010168,135.193091,127.654188,167.605999,167.779855,140.547076,137.611867,88.404029,105.668923,118.934894,86.783842,121.218768,138.082409,101.883689,106.150760,73.904589,15.059199,27.146711,43.164794
31394,168.652469,155.973898,170.705095,117.874903,146.699255,120.388217,104.256618,136.610808,156.946768,114.556163,133.138141,160.223160,139.279606,147.068660,145.603811,69.259938,13.398526,25.727280,38.737302
8626,145.463054,158.127090,126.250436,163.181722,159.850098,154.915528,146.200033,122.636837,146.515446,146.767463,139.495319,170.617917,172.095265,145.387446,105.673108,61.719801,12.089323,24.588492,31.683527
45318,153.182543,134.751129,128.066660,171.197861,171.214088,140.947246,159.418120,171.336508,168.666516,126.583010,86.603363,144.075277,122.028813,103.059018,128.820194,70.181725,12.892734,25.025723,42.661468
49222,129.554583,152.069726,139.920190,176.216415,165.134823,152.455204,176.774797,159.075632,160.580122,172.251860,156.539290,176.401116,104.246252,125.695230,166.127454,74.985223,12.890936,21.703347,37.791730

In [ ]:
X_test.head()

# **6. Random Forest Classifier model with default parameters** <a class="anchor" id="13"></a>

[Table of Contents](#0.1)

In [20]:
# import Random Forest classifier

from sklearn.ensemble import RandomForestClassifier



# instantiate the classifier 

rfc = RandomForestClassifier(random_state=0)



# fit the model

rfc.fit(X_train, y_train)



# Predict the Test set results

y_pred = rfc.predict(X_test)



# Check accuracy score 

from sklearn.metrics import accuracy_score

print('Model accuracy score with 10 decision-trees : {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

ValueError: could not convert string to float: '[0.4305216670036316, 1.0001001358032227, 0.0]'

Here, I have build the Random Forest Classifier model with default parameter of `n_estimators = 10`. So, I have used 10 decision-trees to build the model. Now, the number of decision tress will be increased to 100.

# **7. Random Forest Classifier model with parameter n_estimators=100** <a class="anchor" id="14"></a>

[Table of Contents](#0.1)

In [ ]:
# instantiate the classifier with n_estimators = 100

rfc_100 = RandomForestClassifier(n_estimators=100, random_state=0)



# fit the model to the training set

rfc_100.fit(X_train, y_train)



# Predict on the test set results

y_pred_100 = rfc_100.predict(X_test)



# Check accuracy score 

print('Model accuracy score with 100 decision-trees : {0:0.4f}'. format(accuracy_score(y_test, y_pred_100)))

[Go to Top](#0)